services:
  mysql-master:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${HOST_PORT}:3306"
    volumes:
      - ${DATA_DIR}:/var/lib/mysql
      - ${LOGS_DIR}:/var/log/mysql
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
    command: --server-id=${SERVER_ID} --log_bin=mysql-bin --binlog_format=ROW
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

networks:
  mysql-network:
    driver: bridge
